name: Build and test

on:
 - pull_request

jobs:
 build:

  runs-on: ubuntu-22.04

  strategy:
   matrix:
    node-version: [ 18, 20, 22 ]

  steps:
   - name: Clone repository
     uses: actions/checkout@v2

   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     with:
      node-version: ${{ matrix.node-version }}

   - name: Cache node modules
     uses: actions/cache@v1
     with:
      path: ~/.npm
      key: ${{ runner.os }}-node-v${{ matrix.node }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}
      restore-keys: |
       ${{ runner.OS }}-node-v${{ matrix.node }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}
       ${{ runner.OS }}-node-v${{ matrix.node }}-

   - name: Install
     run: yarn install --frozen-lockfile

   - name: Test
     run: yarn test
